# # Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1
# # Use a package of configuration called an orb.
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1
# # Orchestrate or schedule a set of jobs
# workflows:
#   # Name the workflow "welcome"
#   welcome:
#     # Run the welcome/run job in its own container
#     jobs:
#       - welcome/run

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
    
  deploy:
    docker:
      - image: circleci/node:7
      steps:
        - checkout
        - run:
            name: Deploy main to Digital Ocean
             command: |
              ssh -oStrictHostKeyChecking=no - v root@104.238.130.168 "cd ~/todo-app; git pull; npm install; node app.js" 



workflows:
  version: 2
  example:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
